### ISSUE TITLE
Profile picture is pixelized/compressed?

### ISSUE THREAD

**Issue by j-clinton** [cobidev/gatsby-simplefolio#20]
Is there a way to make the profile picture less pixelized/compressed?

**Comment by j-clinton** [comment]
Fixed it, added quality: 100 to allImageSharp in AboutImg.jsx

**Comment by j-clinton** [comment]
Found a fix. Let me know if you want me to make a pull request.

**Comment by MrBudo** [comment]
How did you do that ?
