### ISSUE TITLE
Meta Tag mockData not working

### ISSUE THREAD

**Issue by summer-cook** [cobidev/gatsby-simplefolio#46]
Hi @cobidev 

I just set up my portfolio with gatsby simplefolio but I am running into an issue where the meta description is still rendering "Lorem Ipsum..." even though i changed the info in the data.js file.

I tried deleting the placeholder "Lorem Ipsum" from everywhere in the project as well as editing the React Helmet tags in index.js directly but this is still what pops up when i try to link my portfolio on linkedin.

It is hosted on Netlify here: https://summercook-dev.netlify.app/
And the repo is here: https://github.com/summer-cook/my-portfolio

I also tried to run
$ gatsby clean

& uninstalled/reinstalled node modules.

Is there something I am missing? Thank you!

<img width="334" alt="Screen Shot 2021-01-19 at 7 54 18 AM" src="https://user-images.githubusercontent.com/73361970/105110215-ffd73e80-5a72-11eb-883b-05996770f08a.png">

**Comment by sakmanal** [comment]
You can try add meta tags inside the head element of html.js
check here: [metaTags](https://metatags.io/)

**Comment by summer-cook** [comment]
Hi @sakmanal, thanks for the suggestion but i figured it out. It was actually an issue with Linkedin's cache pulling old data. 

For anyone dealing with this issue, try sending your profile link in a message on linkedin with  **/?latest** appended to the end of the url - this refreshes Linkedin's cache and forces it to make a new request with your updated meta data :)
