### ISSUE TITLE
website display on load

### ISSUE THREAD

**Issue by frankgomezdev** [cobidev/gatsby-simplefolio#49]
i've noticed during the initial load up of the webpage, it displays the text information that is included in the template and then about after 2-3 seconds, it reloads to the text that I input. is there anyway to fix this?

**Comment by ben-redd** [comment]
I know you closed this issue already, but I was wondering if you ever found a solution? I'm having the same issue and trying to think of a way to fix it other than just hard coding the text included in the template to match the rest of my inputs.
