### ISSUE TITLE
Install Gatsby Simplefolio change text

### ISSUE THREAD

**Issue by master30112001** [cobidev/gatsby-simplefolio#58]
When you open the website, you get an option to install the website, and there the Name is 
Gatsby Simplefolio... which I would like to edit. But didn't find any way to do that.
Can you please help me to change the text? Thankyou in advance :)

![24](https://user-images.githubusercontent.com/64365467/115136929-a31efc00-a040-11eb-908c-c1251890b4f2.jpeg)

**Comment by npiyush97** [comment]
gatsby-config.js / options / name

**Comment by master30112001** [comment]
Thank you so much @npiyush97 :)  !!
